global:
  scrape_interval:     15s
  evaluation_interval: 30s

scrape_configs:
  - job_name:       'otlp'
    static_configs:
      - targets: ['otel-collector:5317']
  - job_name: 'es'
    static_configs:
      - targets: ['opensearch_exporter:9114']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb_exporter:9216']
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgresql_exporter:9187']
